# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-05-31 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control_Anciano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dieta_asignada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Control_Joven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuma', models.BooleanField(default=False)),
                ('annios_fumando', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Control_Ninno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacion_peso_estatura', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('historia', models.IntegerField()),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('consultas', models.ManyToManyField(blank=True, related_name='consultas', to='api.Estado_Consulta')),
            ],
        ),
        migrations.AddField(
            model_name='control_ninno',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Paciente'),
        ),
        migrations.AddField(
            model_name='control_joven',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Paciente'),
        ),
        migrations.AddField(
            model_name='control_anciano',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Paciente'),
        ),
    ]
