# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-05-31 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='consultas',
        ),
        migrations.DeleteModel(
            name='Estado_Consulta',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
