# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-06-01 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_estado_consulta_servicio_servicio_consultas'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='consultas',
            field=models.ManyToManyField(blank=True, related_name='consultas', through='api.Servicio_Consultas', to='api.Estado_Consulta'),
        ),
    ]
