# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-06-01 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_servicio_consultas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control_ninno',
            name='relacion_peso_estatura',
            field=models.CharField(choices=[(1, '1-NORMAL'), (2, '2-BAJO PESO'), (3, '3-DESNUTRIDO'), (4, '4-SOBREPESO')], max_length=1, verbose_name='Relacion Peso Estatura'),
        ),
    ]
