# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-06-01 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210531_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control_ninno',
            name='relacion_peso_estatura',
            field=models.CharField(choices=[('1', '1-NORMAL'), ('2', '2-BAJO PESO'), ('3', '3-DESNUTRIDO'), ('4', '4-SOBREPESO')], max_length=1, verbose_name='Relacion Peso Estatura'),
        ),
        migrations.AlterField(
            model_name='servicio_consultas',
            name='estado_consulta',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.Estado_Consulta'),
        ),
        migrations.AlterField(
            model_name='servicio_consultas',
            name='servicio',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='api.Servicio'),
        ),
    ]
