# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-06-03 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210531_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio_consultas',
            name='profesional',
        ),
        migrations.AddField(
            model_name='paciente',
            name='prioridad',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profesional',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Servicio'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='servicio_consultas',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Servicio'),
        ),
    ]
