# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-06-03 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210603_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='servicio',
        ),
        migrations.AddField(
            model_name='servicio',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Profesional'),
        ),
    ]
